interface Experience {
  start: string
  end: string
  company: string
  role: string
  tech_stack: string[]
  achievements: string[]
}

export const EXPERIENCES: Experience[] = [
  {
    start: 'Jun 24',
    end: 'Oct 25',
    company: 'Bitlabs Academy',
    role: 'Software Engineer',
    tech_stack: [
      'React',
      'TanStack Router',
      'Golang',
      'GraphQL',
      'LangChain',
      'Whisper',
      'Alibaba Cloud Kubernetes',
      'HashiCorp stack',
      'Nomad',
      'Consul',
      'Vault',
      'Terraform',
    ],
    achievements: [
      'Developed AI powered LMS platforms (‘Yes Academy’, ‘Yes LMS’) using React, TanStack Router, Golang, and GraphQL.',
      'Integrated LangChain + Whisper for real-time speech-to-text and AI learning assistant.',
      'Migrated from Alibaba Cloud Kubernetes to HashiCorp stack (Nomad, Consul, Vault, Terraform), achieving 80% cost savings.',
      'Optimized GraphQL resolvers and data loaders, reducing average response time by 40%.',
    ],
  },
  {
    start: 'Sep 22',
    end: 'Jun 24',
    company: 'Good Games Guild (GGG)',
    role: 'Senior Backend Engineer / Project Manager',
    tech_stack: [
      'Node.js',
      'TypeScript',
      'MongoDB',
      'Redis',
      'NATS',
      'MQTT',
      'Docker',
      'GCP Kubernetes',
      'HashiCorp Stack',
      'Nomad',
      'Consul',
      'Vault',
      'RainbowKit',
      'Wagmi',
      'Supabase',
    ],
    achievements: [
      'Architected scalable microservices with Node.js, TypeScript, MongoDB, Redis, NATS, and MQTT.',
      'Optimized Docker containers, reducing image size by 60% and cutting deployment time by 45%.',
      'Migrated infrastructure from GCP Kubernetes to HashiCorp Stack (Nomad, Consul, Vault), reducing costs by 25%.',
      'Wrote detailed technical documentation and maintained SLA compliance above 99.9%.',
      'Led end-to-end development of blockchain staking features for Hightable and Metaverspad, integrating RainbowKit, Wagmi, and Supabase for wallet connectivity, on-chain interactions, and user authentication boosting platform engagement by 50%.',
      'Built and maintained supporting backend services (Node.js, TypeScript) for staking logic, reward distribution, and real-time balance tracking.',
    ],
  },
  {
    start: 'Aug 22',
    end: 'Aug 23',
    company: 'Infosys Solusi Terpadu',
    role: 'Senior Frontend Engineer',
    tech_stack: ['React', 'Docker', 'CSP'],
    achievements: [
      'Collaborated with Pegadaian Emas and banking clients (CIMB, Mayapada, Mandiri) for internal systems.',
      'Led 25+ engineers across multiple projects and refactored legacy web applications.',
      'Defined and enforced company-wide frontend standards for React applications, enhancing long-term maintainability.',
      'Strengthened application security (e.g., CSP, dependency auditing) and optimized Docker container size to improve CI/CD efficiency.',
    ],
  },
  {
    start: 'Dec 21',
    end: 'May 24',
    company: 'CariGuru',
    role: 'Fullstack Engineer / Tech Lead',
    tech_stack: [
      'Express',
      'TypeScript',
      'MongoDB',
      'Redis',
      'React',
      'Tailwind',
      'Nomad',
      'Consul',
    ],
    achievements: [
      'Built and maintained 6+ microservices—including Payment, Student, and Webinar systems handling 10K+ daily transactions.',
      'Implemented Express, TypeScript, MongoDB, and Redis backend; React + Tailwind for frontend.',
      'Introduced Nomad + Consul for orchestration, reducing downtime by 50% and cutting infra costs by 20%.',
      'Introduced Story Pointing to improve sprint planning, balancing workload efficiency by 30%.',
      'Provided technical leadership for a 35+ person tech division, aligning product, design, and engineering teams to ensure timely delivery.',
    ],
  },
  {
    start: 'Aug 21',
    end: 'Jan 23',
    company: 'Lingotalk',
    role: 'Backend Engineer / Tech Lead',
    tech_stack: ['SQL', 'FaunaDB', 'Midtrans'],
    achievements: [
      'Led backend team of 10+ engineers; later managed 25+ cross-functional members (Frontend & Backend).',
      'Migrated SQL database to FaunaDB, improving query latency by 35%.',
      'Integrated Midtrans payment gateway, automating 95% of payment flows and boosting success rate by 30%.',
      'Designed and implemented appointments scheduling system, supporting 10K+ monthly bookings.',
      'Awarded Employee of the Month (Nov 2021) for leadership and delivery excellence.',
    ],
  },
  {
    start: 'Nov 21',
    end: 'May 22',
    company: 'Blups Asia',
    role: 'Fullstack Engineer',
    tech_stack: ['Next.js', 'Framer Motion', 'Tailwind CSS', 'Golang', 'Sanity CMS', 'AWS', 'GCP'],
    achievements: [
      'Built fullstack features for internal cargo tracking and e-commerce tools using Next.js (with Framer Motion and Tailwind CSS) and lightweight Golang services.',
      'Integrated with Sanity CMS for content management and streamlined data flow between frontend and backend layers.',
      'Integrated AWS and GCP services, improving deployment stability by 40%.',
      'Optimized backend architecture, reducing response time by 25% and improving scalability for high-traffic environments.',
    ],
  },
  {
    start: 'Jan 21',
    end: 'Dec 21',
    company: 'Sinarmas',
    role: 'Software Engineer',
    tech_stack: ['Spring Boot', 'RESTful APIs', 'Java'],
    achievements: [
      'Developed internal banking tools by building RESTful APIs (Spring Boot) and frontend interfaces for operational teams.',
      'Focused on secure, maintainable code for internal-use applications supporting functions like Virtual Accounts, Bulk Payments, and QR Merchant services.',
      'Rewrote legacy Java microservices using Spring Boot, reducing maintenance time by 40%.',
      'Collaborated with multiple divisions to define business requirements and improve integration flow.',
      'Integrated B2B and internal APIs, increasing data processing throughput by 25%.',
    ],
  },
]
